# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Detroit-School-Transport' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'UITextField+Shake', '~> 1.1'
  # Pods for Detroit-School-Transport
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'Detroit-School-TransportTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Detroit-School-TransportUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
